# Generated by Django 4.2.3 on 2023-07-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='purpose',
            field=models.CharField(choices=[('enquiry', 'ENQUIRY'), ('place order', 'PLACE ORDER'), ('return', 'RETURN'), ('payment', 'PAYMENT')], default='user', max_length=20),
        ),
    ]
