# Generated by Django 4.2.3 on 2023-07-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_age_person_dob_person_email_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='purpose',
            field=models.CharField(choices=[('select', 'SELECT'), ('enquiry', 'ENQUIRY'), ('place order', 'PLACE ORDER'), ('return', 'RETURN'), ('payment', 'PAYMENT'), ('other', 'OTHER')], default='user', max_length=20),
        ),
    ]
